name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install dependencies
        run: |
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Run security scans
        run: |
          bundle exec brakeman -q
          bundle exec bundler-audit check --update

      - name: Run RuboCop
        run: |
          bundle exec rubocop --fail-level W

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          echo "$SECRET_KEY" > KeyTwo.pem
          chmod 600 KeyTwo.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i KeyTwo.pem ubuntu@$PUBLIC_IP << 'EOF'
            set -e
            cd ~/projectApp
            git pull origin main
            bundle install
            rails db:migrate
          EOF

      - name: Clean up
        run: |
          rm -f KeyTwo.pem
