name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > CADFinal.pem
          chmod 600 CADFinal.pem
      
      - name: Set executable permissions for bin files
        run: |
          chmod +x bin/*

      - name: Deploy to EC2
        run: |
          INSTANCE_ID="i-01aa74476ed57c04e"
          PUBLIC_IP=18.208.110.60
          SSH_PORT=3003

          # Ensure you're using the correct EC2 user
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT -i CADFinal.pem ec2-user@$PUBLIC_IP << 'EOF'
            set -e
            # Ensure the directory exists, or create it
            mkdir -p /home/ec2-user/railsProjects
            cd /home/ec2-user/railsProjects
            git pull origin main
            RAILS_ENV=production bundle install
            RAILS_ENV=production rails db:migrate
          EOF

      - name: Clean up
        run: |
          rm -f CADFinal.pem
